### ISSUE TITLE
Return value of Game::worldPosToZonePos() must be of the type array, boolean returned

### ISSUE THREAD

**Issue by DerEnderman** [TrinityCore/aowow#34]
```23:23:42           - reading and merging achievement_criteria.dbc for locales 0, 3
23:23:48  [OK]     - subscript 'achievementcriteria' returned sucessfully
23:23:48          SqlGen::generate() - filling aowow_areatrigger with data
23:23:49             - fetching taverns
23:24:27             - calculation teleporter coordinates
Exception - Return value of Game::worldPosToZonePos() must be of the type array, boolean returned
   /var/www/vhosts/sdsdsd.de/httpdocs/aowow/includes/game.php(267)
#0 /var/www/vhosts/sdsdsd.de/httpdocs/aowow/setup/tools/sqlgen/areatrigger.func.php(43): Game::worldPosToZonePos(189, 1053.48, 1688.99)
#1 /var/www/vhosts/sdsdsd.de/httpdocs/aowow/setup/tools/sqlGen.class.php(205): class@anonymous->generate(Array)
#2 /var/www/vhosts/sdsdsd.de/httpdocs/aowow/setup/tools/clisetup/sql.func.php(33): SqlGen::generate('areatrigger', Array)
#3 /var/www/vhosts/sdsdsd.de/httpdocs/aowow/setup/setup.php(71): sql()
#4 /var/www/vhosts/sdsdsd.de/httpdocs/aowow/aowow(10): require('/var/www/vhosts...')
```

Some ideas?!

**Comment by Sarjuuk** [comment]
Ultimately a DB error, as the query only returns a boolean if there is a field mismatch or some other structural problem. 

This should be caught from 366a0f2040313c657a3463112bcacbf2feac6bab onward.
